FROM golang:1.22-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git ca-certificates

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /bot ./cmd/bot

FROM alpine:3.19

RUN apk add --no-cache ca-certificates tzdata

COPY --from=builder /bot /bot

EXPOSE 8081

ENTRYPOINT ["/bot"]
