apiVersion: v1
kind: Service
metadata:
  name: bot-service
  namespace: dropradar
spec:
  selector:
    app: dropradar
    component: bot
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  type: ClusterIP
