apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dropradar-ingress
  namespace: dropradar
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: bot.dropradar.dev
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: bot-service
            port:
              number: 8081
